# 無効化するルール
disabled_rules:
  - trailing_whitespace     # 行末の空白を許可
  - line_length             # 行の長さは別途カスタマイズ

# 明示的に有効化するルール
opt_in_rules:
  - empty_count             # count == 0 の代わりに isEmpty を使用
  - missing_docs            # 公開APIにドキュメントを要求
  - force_unwrapping        # 強制アンラップを禁止

# 検査対象外のディレクトリ
excluded:
  - Carthage
  - Pods
  - build
  - SilentCue Watch AppTests
  - SilentCue Watch AppUITests

# 行の長さ制限
line_length:
  warning: 120
  error: 200

# 関数本体の長さ制限
function_body_length:
  warning: 50
  error: 100

# 型定義の長さ制限
type_body_length:
  warning: 300
  error: 500

# ファイルの長さ制限
file_length:
  warning: 500
  error: 1000

# 循環的複雑度の制限
cyclomatic_complexity:
  warning: 10
  error: 20

# ネスト制限
nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

# 識別子の命名制限
identifier_name:
  min_length: 2
  max_length: 40
  excluded:      # 短い一般的な変数名を許可
    - id
    - URL
    - x
    - y
    - to
    - at
    - of
    - from
    - with
    