# $ mint run xcodegen

name: SilentCue
options:
  bundleIdPrefix: com.akitorahayashi.SilentCue
path: SilentCue.xcodeproj
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 1.19.0
  CasePaths:
    url: https://github.com/pointfreeco/swift-case-paths
    from: 1.6.1
  Dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    from: 1.9.1
  Perception:
    url: https://github.com/pointfreeco/swift-perception
    from: 1.5.1

targets:
  "SilentCue Watch App":
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources: 
      - "SilentCue Watch App"
    dependencies:
      - package: ComposableArchitecture
    info:
      path: SilentCue-Watch-App-Info.plist
      properties:
        UIBackgroundModes: []
        WKApplicationRefreshBackgroundModes: 
          - background-refresh-on-schedule
        WKBackgroundModes:
          - workout-processing
          - background-fetch
          - background-processing
        WKWatchOnly: YES
        WKBackgroundRefresh: YES
        WKBackgroundTasks:
          - background-fetch
          - background-processing
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.SilentCue.WatchApp
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        # DEVELOPMENT_TEAM: 

  "SilentCue Watch AppTests":
    type: bundle.unit-test
    platform: watchOS
    deploymentTarget: "10.0"
    sources: 
      - "SilentCue Watch AppTests"
    dependencies:
      - target: "SilentCue Watch App"
      - package: ComposableArchitecture
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.SilentCue.WatchAppTests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SilentCue Watch App.app/SilentCue Watch App"

  "SilentCue Watch AppUITests":
    type: bundle.ui-testing
    platform: watchOS
    deploymentTarget: "10.0"
    sources: 
      - "SilentCue Watch AppUITests"
    dependencies:
      - target: "SilentCue Watch App"
      - package: ComposableArchitecture
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.SilentCue.WatchAppUITests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: "SilentCue Watch App"

schemes:
  "SilentCue Watch App":
    build:
      targets:
        "SilentCue Watch App": all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - "SilentCue Watch AppTests"
        - "SilentCue Watch AppUITests"
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      
  "SilentCue Watch AppTests":
    build:
      targets:
        "SilentCue Watch AppTests": all
    test:
      config: Debug
      targets:
        - "SilentCue Watch AppTests"
        
  "SilentCue Watch AppUITests":
    build:
      targets:
        "SilentCue Watch AppUITests": all
    test:
      config: Debug
      targets:
        - "SilentCue Watch AppUITests" 