# $ mint run xcodegen generate

name: SilentCue
options:
  bundleIdPrefix: com.akitorahayashi
  deploymentTarget:
    watchOS: 10.0

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: 5.9
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    ENABLE_BITCODE: NO

packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: "1.19.0"
  Dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    from: "1.2.0"
  CasePaths:
    url: https://github.com/pointfreeco/swift-case-paths
    from: "1.1.0"
  SwiftNavigation:
    url: https://github.com/pointfreeco/swift-navigation
    from: "2.3.0"
  Clocks:
    url: https://github.com/pointfreeco/swift-clocks
    from: "1.0.0"

targets:
  "SilentCue Watch App":
    type: application
    platform: watchOS
    sources:
      - path: SilentCue Watch App
    dependencies:
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: Dependencies
        product: Dependencies
      - package: CasePaths
        product: CasePaths
      - package: SwiftNavigation
        product: SwiftNavigation
      - package: Clocks
        product: Clocks
      - target: SCProtocol
      - target: SCShared
      - target: SCLiveService
      - target: SCPreview
        condition: { config: Debug }
      - target: SCMock
        condition: { config: Debug }
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(bundleIdPrefix).SilentCueWatchApp
        DEVELOPMENT_LANGUAGE: en
        GENERATE_INFOPLIST_FILE: NO
        ENABLE_BITCODE: NO
      configs:
        Debug: {}
        Release: {}
    info:
      path: SilentCue Watch App/Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleDisplayName: SilentCue
        WKApplicationRefreshBackgroundTaskModes:
          - background-refresh-on-schedule
        WKBackgroundTasks:
          - background-fetch
          - background-processing
        WKBackgroundRefresh: true
        WKCompanionAppBundleIdentifier: ""
        WKApplication: true

  SCProtocol:
    type: library.static
    platform: watchOS
    sources:
      - path: Infrastructure/SCProtocol
    dependencies:
      - target: SCShared
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: Dependencies
        product: Dependencies
      - package: CasePaths
        product: CasePaths
      - package: SwiftNavigation
        product: SwiftNavigation
      - package: Clocks
        product: Clocks
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(bundleIdPrefix).SilentCueWatchApp.SCProtocol
        GENERATE_INFOPLIST_FILE: NO
      configs:
        Debug: {}
        Release: {}

  SCShared:
    type: library.static
    platform: watchOS
    sources:
      - path: SCShared
    dependencies:
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: Dependencies
        product: Dependencies
      - package: CasePaths
        product: CasePaths
      - package: SwiftNavigation
        product: SwiftNavigation
      - package: Clocks
        product: Clocks
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(bundleIdPrefix).SilentCueWatchApp.SCShared
        GENERATE_INFOPLIST_FILE: NO
      configs:
        Debug: {}
        Release: {}

  SCLiveService:
    type: library.static
    platform: watchOS
    sources:
      - path: Infrastructure/SCLiveService
    dependencies:
      - target: SCProtocol
      - target: SCShared
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: Dependencies
        product: Dependencies
      - package: SwiftNavigation
        product: SwiftNavigation
      - package: Clocks
        product: Clocks
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(bundleIdPrefix).SilentCueWatchApp.SCLiveService
        GENERATE_INFOPLIST_FILE: NO
      configs:
        Debug: {}
        Release: {}

  SCPreview:
    type: library.static
    platform: watchOS
    sources:
      - path: Infrastructure/SCPreview
    dependencies:
      - target: SCProtocol
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: Dependencies
        product: Dependencies
      - package: SwiftNavigation
        product: SwiftNavigation
      - package: Clocks
        product: Clocks
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(bundleIdPrefix).SilentCueWatchApp.SCPreview
        GENERATE_INFOPLIST_FILE: NO
      configs:
        Debug: {}
        Release: {}

  SCMock:
    type: library.static
    platform: watchOS
    sources:
      - path: Infrastructure/SCMock
    dependencies:
      - target: SCProtocol
      - target: SCShared
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: Dependencies
        product: Dependencies
      - package: SwiftNavigation
        product: SwiftNavigation
      - package: Clocks
        product: Clocks
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(bundleIdPrefix).SilentCueWatchApp.SCMock
        GENERATE_INFOPLIST_FILE: NO
      configs:
        Debug: {}
        Release: {}

  "SilentCue Watch AppTests":
    type: bundle.unit-test
    platform: watchOS
    sources:
      - path: SilentCue Watch AppTests
    dependencies:
      - target: "SilentCue Watch App"
      - target: SCMock
      - target: SCShared
      - target: SCProtocol
      - target: SCLiveService
      - target: SCPreview
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: Dependencies
        product: Dependencies
      - package: CasePaths
        product: CasePaths
      - package: SwiftNavigation
        product: SwiftNavigation
      - package: Clocks
        product: Clocks
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(bundleIdPrefix).SilentCueWatchAppTests
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_BITCODE: NO
      configs:
        Debug: {}
        Release: {}

  "SilentCue Watch AppUITests":
    type: bundle.ui-testing
    platform: watchOS
    sources:
      - path: SilentCue Watch AppUITests
    dependencies:
      - target: "SilentCue Watch App"
      - target: SCShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(bundleIdPrefix).SilentCueWatchAppUITests
        DEVELOPMENT_TARGET: $(TARGET_DEVICE_IDENTIFIER)
        TEST_TARGET_NAME: "SilentCue Watch App"
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_BITCODE: NO
      configs:
        Debug: {}
        Release: {}

schemes:
  "SilentCue Watch App":
    build:
      targets:
        "SilentCue Watch App": all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - "SilentCue Watch AppTests"
        - "SilentCue Watch AppUITests"
    archive:
      config: Release

  "SilentCue Watch AppTests":
    build:
      targets:
        "SilentCue Watch AppTests": test
    test:
      config: Debug
      targets:
        - "SilentCue Watch AppTests"

  "SilentCue Watch AppUITests":
    build:
      targets:
        "SilentCue Watch AppUITests": test
    test:
      config: Debug
      targets:
        - "SilentCue Watch AppUITests"
