name: Build Unsigned Archive

on:
  workflow_call:

jobs:
  archive:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
          
      - name: Cache SPM dependencies
        uses: actions/cache@v4
        with:
          path: |
            DerivedData/Build/SourcePackages/checkouts
            ~/.swiftpm/xcode-package-cache
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
          
      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build Archive
        id: build_archive
        shell: bash
        run: |
          source .github/scripts/build-steps/build-archive.sh
          source .github/scripts/common/prerequisites.sh
          check_xcpretty
          build_archive_step
          exit $?
        continue-on-error: true

      - name: Verify Archive
        id: verify_archive
        shell: bash
        if: steps.build_archive.outcome == 'success'
        run: |
          source .github/scripts/build-steps/build-archive.sh
          verify_archive_step

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-archive
          path: ./ci-outputs/production/archives/SilentCue.xcarchive
          if-no-files-found: warn
          retention-days: 7