name: Build Unsigned Archive

on:
  workflow_call:

jobs:
  archive:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Mint packages
        uses: actions/cache@v4
        id: cache-mint-packages
        with:
          path: ${{ github.workspace }}/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Setup Mint and Generate Project
        run: make setup-mint codegen

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Build Unsigned Archive
        run: make archive

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-archive
          path: ci-outputs/production/archives/SilentCue.xcarchive
          retention-days: 7