name: Build Unsigned Archive

on:
  workflow_call:

jobs:
  archive:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Project
        run: make codegen

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Build Unsigned Archive
        run: make build-unsigned-archive

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-archive
          path: ci-outputs/production/archives/SilentCue.xcarchive
          retention-days: 7