name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  lint:
    name: Format and Lint
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Mint)
      run: |
        brew install mint
        mint bootstrap

    - name: Run SwiftFormat
      run: mint run swiftformat .

    - name: Run SwiftLint
      run: mint run swiftlint --strict

    - name: Check for changes
      run: |
        git diff --exit-code || { echo "コードフォーマットの問題が見つかりました"; exit 1; } 