name: Code Quality Checks

on:
  workflow_call:
    outputs:
      result:
        description: "Check Result"
        value: ${{ jobs.check.outputs.result }}

jobs:
  check:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Mint packages
        uses: actions/cache@v4
        id: cache-mint-packages
        with:
          path: ${{ github.workspace }}/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Setup Mint
        run: brew install mint

      - name: Run Code Quality Checks
        run: make quality

    outputs:
      result: ${{ job.status }} 