name: Copilot PR Review
on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: number

jobs:
  copilot-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read          # checkout 用
      pull-requests: write    # reviewer 追加
      issues: write           # エラー時のコメント追加 ★忘れがち
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Request review from Copilot
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = Number(process.env.PR_NUMBER);
            try {
              const res = await github.rest.pulls.requestReviewers({
                ...context.repo,
                pull_number: pr,
                reviewers: ['github-copilot']
              });
              core.notice(`Copilot reviewer request status: ${res.status}`);
            } catch (error) {
              core.warning(`Failed to add Copilot: ${error.message}`);
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: pr,
                body: `GitHub Copilot にレビューを依頼しようとしましたが失敗しました。\n\n**エラー:** ${error.message}\n\n- Copilot のコードレビュー機能が有効か\n- "github-copilot" を reviewer に指定しているか\n- ワークフローに \`issues: write\` 権限があるか\nを確認してください。`
              });
              throw error;   // ジョブを失敗させて可視化
            }
        env:
          PR_NUMBER: ${{ inputs.pr_number }}
