name: Run Tests

on:
  workflow_call:
    outputs:
      test_result:
        description: "Test Result"
        value: ${{ jobs.report-status.outputs.test_result }}

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Mint Cache
        uses: actions/cache@v4
        id: cache-mint-packages-tests
        with:
          path: ~/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Generate Project
        run: make codegen

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Run Unit Tests
        id: unit_tests
        run: make unit-test

      - name: Run UI Tests
        id: ui_tests
        run: make ui-test

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results-${{ github.run_id }}
          path: ci-outputs/test-results/unit
          retention-days: 7

      - name: Upload UI Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results-${{ github.run_id }}
          path: ci-outputs/test-results/ui
          retention-days: 7

  report-status:
    needs: [test]
    runs-on: ubuntu-latest
    if: always()
    outputs:
      test_result: ${{ steps.set_status.outputs.result }}
    steps:
      - name: Check test job outcomes and set final status
        id: set_status
        run: |
          echo "Test job outcome: ${{ needs.test.result }}"
          if [[ "${{ needs.test.result }}" == "success" ]]; then
            echo "Test job succeeded."
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "Test job failed or was skipped."
            echo "result=failure" >> $GITHUB_OUTPUT
          fi 