name: Run Tests

on:
  workflow_call:
    outputs:
      test_result:
        description: "Test Result"
        value: ${{ jobs.report-status.outputs.test_result }}

jobs:
  # Combined setup, build, and test job using Makefile
  test:
    runs-on: macos-latest
    # Add outputs if needed to report individual test step success/failure
    # outputs:
    #   unit_test_outcome: ${{ steps.unit_tests.outcome }}
    #   ui_test_outcome: ${{ steps.ui_tests.outcome }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Mint
        run: brew install mint

      - name: Generate Project
        run: make codegen

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2' # Keep explicit Xcode version

      # --- Build & Test Steps ---
      # Makefile handles build-for-testing dependency internally

      - name: Run Unit Tests
        id: unit_tests
        run: make unit-test

      - name: Run UI Tests
        id: ui_tests
        run: make ui-test

      # --- Artifact Upload ---
      # Makefile creates output in predefined locations

      - name: Upload Unit Test Results
        if: always() # Always upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results-${{ github.run_id }}
          path: ci-outputs/test-results/unit # Path defined in Makefile
          retention-days: 7

      - name: Upload UI Test Results
        if: always() # Always upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results-${{ github.run_id }}
          path: ci-outputs/test-results/ui # Path defined in Makefile
          retention-days: 7

  report-status:
    needs: [test] # Depends on the combined test job
    runs-on: ubuntu-latest
    if: always()
    outputs:
      test_result: ${{ steps.set_status.outputs.result }}
    steps:
      - name: Check test job outcomes and set final status
        id: set_status
        run: |
          # Access step outcomes if defined in the 'test' job outputs:
          # Check the overall job outcome for simplicity:
          echo "Test job outcome: ${{ needs.test.result }}"
          if [[ "${{ needs.test.result }}" == "success" ]]; then
            echo "Test job succeeded."
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "Test job failed or was skipped."
            echo "result=failure" >> $GITHUB_OUTPUT
          fi 