name: Run Tests

on:
  workflow_call:
    outputs:
      test_result:
        description: "Test Result"
        value: ${{ jobs.build-and-test.outputs.test_result }}

jobs:
  build-and-test:
    runs-on: macos-latest
    outputs:
      test_result: ${{ steps.test_status.outputs.result }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Make find_simulator script executable
      run: chmod +x .github/scripts/find_simulator.sh

    - name: Select Simulator
      id: select_simulator
      run: |
        SIMULATOR_ID=$(./.github/scripts/find_simulator.sh)
        echo "シミュレータ ID ($SIMULATOR_ID) が選択されました"
        echo "simulator_id=$SIMULATOR_ID" >> $GITHUB_OUTPUT

    - name: Install xcpretty
      run: gem install xcpretty
        
    - name: Create Test Results Directory
      run: mkdir -p test-results/unit test-results/ui
        
    - name: Build for Testing
      run: |
        set -o pipefail
        echo "シミュレータ ID (${{ steps.select_simulator.outputs.simulator_id }}) を使用してテスト用にビルドします"
        xcodebuild build-for-testing \
          -project "SilentCue.xcodeproj" \
          -scheme "SilentCue Watch App" \
          -destination "platform=watchOS Simulator,id=${{ steps.select_simulator.outputs.simulator_id }}" \
          -derivedDataPath ./xcbuild \
          -configuration Debug \
          -skipMacroValidation \
          CODE_SIGNING_ALLOWED=NO \
          | xcpretty -c
      
    - name: Run Unit Tests
      id: unit_tests
      run: |
        set -o pipefail
        echo "シミュレータ ID (${{ steps.select_simulator.outputs.simulator_id }}) を使用してユニットテストを実行します"
        xcodebuild test-without-building \
          -project "SilentCue.xcodeproj" \
          -scheme "SilentCue Watch AppTests" \
          -destination "platform=watchOS Simulator,id=${{ steps.select_simulator.outputs.simulator_id }}" \
          -derivedDataPath ./xcbuild \
          -enableCodeCoverage NO \
          -resultBundlePath ./test-results/unit/TestResults.xcresult \
          | xcbeautify --report junit --report-path ./test-results/unit/junit.xml
        
        echo "UNIT_TEST_STATUS=$?" >> $GITHUB_ENV
        ls -la ./test-results/unit/
      continue-on-error: false
          
    - name: Run UI Tests
      id: ui_tests
      run: |
        set -o pipefail
        echo "シミュレータ ID (${{ steps.select_simulator.outputs.simulator_id }}) を使用して UI テストを実行します"
        xcodebuild test-without-building \
          -project "SilentCue.xcodeproj" \
          -scheme "SilentCue Watch AppUITests" \
          -destination "platform=watchOS Simulator,id=${{ steps.select_simulator.outputs.simulator_id }}" \
          -derivedDataPath ./xcbuild \
          -enableCodeCoverage NO \
          -resultBundlePath ./test-results/ui/TestResults.xcresult \
          | xcbeautify --report junit --report-path ./test-results/ui/junit.xml
          
        echo "UI_TEST_STATUS=$?" >> $GITHUB_ENV
        ls -la ./test-results/ui/
      continue-on-error: false
      
    - name: Set Test Status
      id: test_status
      run: |
        if [ "$UNIT_TEST_STATUS" == "0" ] && [ "$UI_TEST_STATUS" == "0" ]; then
          echo "result=success" >> $GITHUB_OUTPUT
        else
          echo "result=failure" >> $GITHUB_OUTPUT
        fi
      
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./test-results
        retention-days: 7 